train:
  batch_size: 64
  patience: 20
  # agc_clip: 0.1
  num_gpu: 1
  train_epochs_max: 100
  loss: "mse, mse_plus_pearsonr" 
  optimizer: "adam, sgd" # default sgd. Options: adam; adamw; sgd; momentum.
  learning_rate: 0.0001
  decay_rate: 0.98 # default 0.96.
  warmup_steps: 4000
  # initial_learning_rate: 0.0001
  # maximal_learning_rate: 0.001
  # final_learning_rate: 0.00001
  # train_epochs_cycle1: 20

  adam_beta1: 0.9 
  adam_beta2: 0.999 # default 0.999.
  

model:
  num_bins: 1024
  num_tracks: 106
  activation: "relu, gelu"
  norm_type: "batch"
  augment_r: True
  augment_shift: 1, 2, 3, 0
  bn_momentum: 0.9
  kernel_initializer: "lecun_normal"
  l2_scale: 2.0e-8
  trunk:
    - name: "conv_dna"
      conv_type: "maxpooling1d"
      filters: 256
      kernel_size: 20
      norm_type: "null"
      activation: "linear"
      pool_size: 2
      pool_type: "softmax"
    - name: "res_tower"
      filters_init: 312
      filters_end: 512
      divisible_by: 32
      kernel_size: 10
      num_convs: 1
      pool_size: 2
      pool_type: "softmax" # or maxpooling1d
      repeat: 4
    - name: "transformer"
      heads: 8
      key_size: 64 # The size of each key and query embedding per head.
      dropout: 0
      num_position_features: 1024
      dense_expansion: 0
      mha_l2_scale: 0 # default 0, 0意味着对权重不使用惩罚项。 
      mha_initializer: "he_normal" # 使用正态分布初始化权重，适合ReLU 激活函数
      attention_dropout: 0
      position_dropout: 0
    
    - name: "unet_conv"
      kernel_size: 3
      upsample_conv: True
    - name: "unet_conv"
      kernel_size: 3
      upsample_conv: True
      
    - name: "global_pool"
      pool_type: "attention"
      pool_axis: 1



  head_rice:
    - name: "dense_head"
      # hidden_units: 128 # default None. If setting, will add a dense layer with this number of units before the final output layer.
      units: 23 # number of targets
      activation: "softplus"

  
