#!/usr/bin/env python3
"""
Paddy Motif Plotting Script

This script creates publication-quality plots for motif analysis results,
similar to Figure 3 in the reference paper. It reads the integrated H5 file
generated by motif_metadata_summary.py and creates various visualizations.

Usage:
    python paddy_motif_plot.py --input integrated_motifs.h5 --output_dir plots/
"""

import argparse
import os
import sys
import numpy as np
import pandas as pd
import h5py
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.ticker import FormatStrFormatter
import seaborn as sns
from scipy.stats import spearmanr, ranksums
import warnings
warnings.filterwarnings('ignore')

# PWM sequence logo visualization code
import matplotlib as mpl
from matplotlib.text import TextPath
from matplotlib.patches import PathPatch
from matplotlib.font_manager import FontProperties
from matplotlib import gridspec
import colorsys


def lighten_color(color, amount=0.5):
    """Function to interpolate color, from explore_modisco_5_tissues.py"""
    try:
        c = mpl.colors.cnames[color]
    except:
        c = color
    c = colorsys.rgb_to_hls(*mpl.colors.to_rgb(c))
    return colorsys.hls_to_rgb(c[0], 1 - amount * (1 - c[1]), c[2])


class MotifPlotter:
    """
    Main class for creating motif analysis plots.
    """
    
    def __init__(self, h5_file_path, output_dir="plots", grads_dir=None):
        self.h5_file_path = h5_file_path
        self.output_dir = output_dir
        self.grads_dir = grads_dir  # Directory containing tissue_{id}.h5 with seqs/grads
        self.grads_cache = {}  # Cache grads per tissue to avoid repeated IO
        self.tissue_colors = {
            0: '#d62728',    # red
            18: '#1f77b4',   # blue  
            19: '#ff7f0e',   # orange
            20: '#2ca02c',   # green
            22: '#9467bd'    # purple
        }
        
        # Define tissue name mapping (tissue_id -> T{id} format)
        self.tissue_name_map = {}  # Will be populated dynamically
        
        # Define tissue full name mapping (tissue_id -> tissue_{id} format)
        self.tissue_full_name_map = {}  # Will be populated dynamically
        
        # Create output directory
        os.makedirs(output_dir, exist_ok=True)
        
        # Load data
        self.load_data()
    
    def load_data(self):
        """Load data from the integrated H5 file."""
        print(f"Loading data from {self.h5_file_path}")
        
        with h5py.File(self.h5_file_path, 'r') as f:
            # Load global metadata
            self.tissue_indices = f['global_metadata/tissues_analyzed'][()]
            self.n_tissues = len(self.tissue_indices)
            
            # Populate tissue name mappings dynamically
            for tissue_id in self.tissue_indices:
                self.tissue_name_map[tissue_id] = f"T{tissue_id}"
                self.tissue_full_name_map[tissue_id] = f"tissue_{tissue_id}"
            
            # Load motif data
            self.motifs = {}
            motifs_group = f['motifs']
            
            for jaspar_id in motifs_group.keys():
                motif_data = self._load_motif_data(motifs_group[jaspar_id])
                if motif_data:
                    self.motifs[jaspar_id] = motif_data
        
        print(f"Loaded {len(self.motifs)} motifs for {self.n_tissues} tissues")
        print(f"Tissue mappings: {self.tissue_name_map}")
    
    def _load_motif_data(self, motif_group):
        """Load data for a single motif."""
        try:
            motif_data = {
                'jaspar_id': motif_group['metadata/jaspar_id'][()].decode() if 'metadata/jaspar_id' in motif_group else '',
                'consensus_sequence': motif_group['metadata/consensus_sequence'][()].decode() if 'metadata/consensus_sequence' in motif_group else '',
                'tissues': {},
                'cross_tissue_analysis': {}
            }
            
            # Load JASPAR PWM if available
            if 'metadata/jaspar_pwm' in motif_group:
                motif_data['jaspar_pwm'] = motif_group['metadata/jaspar_pwm'][()]
                motif_data['jaspar_motif_name'] = motif_group['metadata/jaspar_motif_name'][()].decode()
            
            # Load tissue-specific data
            if 'tissues' in motif_group:
                for tissue_key in motif_group['tissues'].keys():
                    tissue_id = int(tissue_key.split('_')[1])
                    tissue_data = self._load_tissue_data(motif_group['tissues'][tissue_key])
                    if tissue_data:
                        motif_data['tissues'][tissue_id] = tissue_data
            
            # Load cross-tissue analysis
            if 'cross_tissue_analysis' in motif_group:
                cross_tissue = motif_group['cross_tissue_analysis']
                if 'wilcoxon_test' in cross_tissue:
                    motif_data['cross_tissue_analysis'] = {
                        'p_value': cross_tissue['wilcoxon_test/p_value'][()],
                        's_value': cross_tissue['wilcoxon_test/s_value'][()],
                        'largest_tissue_id': cross_tissue['wilcoxon_test/largest_tissue_id'][()],
                        'second_largest_tissue_id': cross_tissue['wilcoxon_test/second_largest_tissue_id'][()],
                        'largest_q95': cross_tissue['wilcoxon_test/largest_q95'][()],
                        'second_largest_q95': cross_tissue['wilcoxon_test/second_largest_q95'][()]
                    }
            
            return motif_data
            
        except Exception as e:
            print(f"Error loading motif data: {e}")
            return None
    
    def _load_tissue_data(self, tissue_group):
        """Load data for a single tissue."""
        try:
            tissue_data = {}
            
            # Load saliency scores
            if 'seqlets/tissue_saliency_scores' in tissue_group:
                tissue_data['saliency_scores'] = tissue_group['seqlets/tissue_saliency_scores'][()]
            
            # Load statistics
            if 'statistics' in tissue_group:
                stats = tissue_group['statistics']
                tissue_data['n_seqlets'] = stats['n_seqlets'][()]
                
                # Load saliency statistics
                if 'saliency_stats' in stats:
                    saliency_stats = stats['saliency_stats']
                    tissue_data['saliency_stats'] = {
                        'mean': saliency_stats['mean'][()],
                        'median': saliency_stats['median'][()],
                        'q95': saliency_stats['q95'][()],
                        'q05': saliency_stats['q05'][()],
                        'std': saliency_stats['std'][()]
                    }
                
                # Load TOMTOM statistics
                if 'tomtom_stats' in stats:
                    tomtom_stats = stats['tomtom_stats']
                    tissue_data['tomtom_stats'] = {
                        'p_value': tomtom_stats['p_value'][()],
                        'e_value': tomtom_stats['e_value'][()],
                        'q_value': tomtom_stats['q_value'][()]
                    }
            
            return tissue_data
            
        except Exception as e:
            print(f"Error loading tissue data: {e}")
            return None

    def dna_letter_at(self, letter, x, y, yscale=1, ax=None, color=None, alpha=1.0):
        """Draw a DNA letter at a given position."""
        fp = FontProperties(family="DejaVu Sans", weight="bold")
        globscale = 1.35
        
        LETTERS = {
            "T": TextPath((-0.305, 0), "T", size=1, prop=fp),
            "G": TextPath((-0.384, 0), "G", size=1, prop=fp),
            "A": TextPath((-0.35, 0), "A", size=1, prop=fp),
            "C": TextPath((-0.366, 0), "C", size=1, prop=fp)
        }
        
        COLOR_SCHEME = {
            'G': 'orange',
            'A': 'green', 
            'C': 'blue',
            'T': 'red'
        }
        
        text = LETTERS[letter]
        chosen_color = COLOR_SCHEME[letter] if color is None else color
        
        t = mpl.transforms.Affine2D().scale(1*globscale, yscale*globscale) + \
            mpl.transforms.Affine2D().translate(x, y) + ax.transData
        p = PathPatch(text, lw=0, fc=chosen_color, alpha=alpha, transform=t)
        
        if ax is not None:
            ax.add_artist(p)
        
        return p

    def plot_pwm(self, pwm, figsize=(8, 2), plot_y_ticks=True, y_min=None, y_max=None, 
                 save_path=None, title=""):
        """Plot a PWM sequence logo."""
        fig = plt.figure(figsize=figsize)
        ax = plt.gca()
        
        height_base = 0.
        logo_height = 1.0
        
        # Conservation = Max_Bits - Entropy
        conservation = 2. - np.sum(-pwm * np.log2(pwm + 1e-6), axis=1)
        
        # Loop over sequence positions
        for j in range(pwm.shape[0]):
            sort_index = np.argsort(pwm[j, :])
            
            # Loop over nucleotide identities
            for ii in range(4):
                i = sort_index[ii]
                
                # Calculate prob * conservation
                nt_prob = pwm[j, i] * conservation[j]
                
                # Decode letter from nucleotide identity
                nt = ['A', 'C', 'G', 'T'][i]
                
                # Draw letter at position
                if ii == 0:
                    self.dna_letter_at(nt, j + 0.5, height_base, nt_prob * logo_height, ax)
                else:
                    prev_prob = np.sum(pwm[j, sort_index[:ii]]) * logo_height * conservation[j]
                    self.dna_letter_at(nt, j + 0.5, height_base + prev_prob, nt_prob * logo_height, ax)
        
        plt.sca(ax)
        plt.xticks([], [])
        plt.gca().yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
        
        plt.xlim((0, pwm.shape[0]))
        
        if plot_y_ticks:
            plt.yticks(fontsize=10)
        else:
            plt.yticks([], [])
        
        # Set axis limits
        if y_min is not None and y_max is not None:
            plt.ylim(y_min, y_max)
        elif y_min is not None:
            plt.ylim(y_min)
        else:
            plt.ylim(0, 2)
        
        plt.axhline(y=0., color='black', linestyle='-', linewidth=1)
        
        if title:
            plt.title(title, fontsize=10)
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
        
        return fig

    def load_grads_data(self, tissue_id):
        """Load seqs and grads for a tissue from grads_dir/tissue_{tissue_id}.h5 (3D or 4D grads)."""
        if not self.grads_dir:
            return None
        if tissue_id in self.grads_cache:
            return self.grads_cache[tissue_id]
        grads_file = os.path.join(self.grads_dir, f"tissue_{tissue_id}.h5")
        if not os.path.exists(grads_file):
            print(f"Warning: Grads file not found: {grads_file}")
            return None
        try:
            with h5py.File(grads_file, 'r') as f:
                data = {
                    'seqs': np.array(f['seqs']),
                    'grads': np.array(f['grads'])
                }
            self.grads_cache[tissue_id] = data
            # Simple shape log
            try:
                gshape = data['grads'].shape
                print(f"Loaded grads for tissue {tissue_id}: grads shape={gshape}")
            except Exception:
                pass
            return data
        except Exception as e:
            print(f"Error loading grads file {grads_file}: {e}")
            return None

    def _compute_saliency_for_motif_tissue(self, jaspar_id, tissue_id):
        """Compute saliency scores for a motif/tissue from grads H5 and seqlet indices in the integrated H5."""
        grads_data = self.load_grads_data(tissue_id)
        if grads_data is None:
            return np.array([])
        seqs = grads_data['seqs']
        grads = grads_data['grads']

        # Select grads for current tissue if 4D, otherwise use 3D as-is
        if grads.ndim == 4:
            tissue_idx = None
            for i, tid in enumerate(self.tissue_indices):
                if int(tid) == int(tissue_id):
                    tissue_idx = i
                    break
            if tissue_idx is None:
                print(f"Warning: tissue {tissue_id} not found in tissue_indices {list(self.tissue_indices)}")
                return np.array([])
            tissue_grads = grads[:, :, :, tissue_idx]
        elif grads.ndim == 3:
            tissue_grads = grads
        else:
            print(f"Warning: Unexpected grads ndim={grads.ndim} for tissue {tissue_id}")
            return np.array([])

        # Read seqlet indices from integrated H5 lazily
        try:
            with h5py.File(self.h5_file_path, 'r') as f:
                tissue_group_path = f"motifs/{jaspar_id}/tissues/tissue_{tissue_id}"
                if tissue_group_path not in f:
                    return np.array([])
                tissue_group = f[tissue_group_path]
                if 'seqlets' not in tissue_group:
                    return np.array([])
                seqlets_group = tissue_group['seqlets']
                required = ['seqlets_example_idx', 'seqlets_start', 'seqlets_end']
                if not all(k in seqlets_group for k in required):
                    return np.array([])
                example_idx = np.array(seqlets_group['seqlets_example_idx'])
                starts = np.array(seqlets_group['seqlets_start'])
                ends = np.array(seqlets_group['seqlets_end'])
        except Exception as e:
            print(f"Error reading seqlet indices for {jaspar_id} tissue {tissue_id}: {e}")
            return np.array([])

        # Compute mean |seq * grad| per seqlet
        scores = []
        n = len(example_idx)
        for i in range(n):
            ex = int(example_idx[i])
            s = int(starts[i])
            e = int(ends[i])
            if e <= s:
                continue
            try:
                seqlet_seq = seqs[ex, s:e, :]
                seqlet_grad = tissue_grads[ex, s:e, :]
                gradient_saliency = seqlet_seq * seqlet_grad
                score = float(np.mean(np.abs(gradient_saliency)))
                scores.append(score)
            except Exception:
                # Skip malformed indices
                continue
        return np.array(scores)

    def plot_tissue_specific_motifs(self, target_tissue_id=None, max_motifs_per_tissue=3, 
                                   save_prefix="tissue_motifs", n_cols=3, col_width=2.5,
                                   y_min_fixed=-0.01, y_max_fixed=0.05, image_format='png'):
        """
        Plot tissue-specific motifs with PWM logos and saliency distributions.
        Each tissue shows its top hits motifs compared across all tissues.
        """
        # Get all available tissues
        all_tissues = set()
        for motif_data in self.motifs.values():
            all_tissues.update(motif_data['tissues'].keys())
        all_tissues = sorted(list(all_tissues))
        
        print(f"Available tissues: {all_tissues}")
        
        # If target tissue not specified, process all tissues
        if target_tissue_id is None:
            for tissue_id in all_tissues:
                self._plot_single_tissue_motifs(tissue_id, max_motifs_per_tissue, 
                                               save_prefix, n_cols, col_width, 
                                               y_min_fixed, y_max_fixed, image_format)
        else:
            self._plot_single_tissue_motifs(target_tissue_id, max_motifs_per_tissue, 
                                           save_prefix, n_cols, col_width, 
                                           y_min_fixed, y_max_fixed, image_format)
    
    def _plot_single_tissue_motifs(self, target_tissue_id, max_motifs_per_tissue, 
                                  save_prefix, n_cols, col_width, y_min_fixed, y_max_fixed, image_format='png'):
        """Plot motifs for a single target tissue."""
        
        # Find motifs that are significant in the target tissue
        tissue_motifs = []
        for jaspar_id, motif_data in self.motifs.items():
            if target_tissue_id in motif_data['tissues']:
                tissue_data = motif_data['tissues'][target_tissue_id]
                
                # Use different criteria to rank motifs for this tissue
                if 'saliency_stats' in tissue_data:
                    # Use 95th percentile as significance measure
                    significance = tissue_data['saliency_stats'].get('q95', 0)
                elif 'tomtom_stats' in tissue_data:
                    # Use E-value (lower is better)
                    significance = -np.log10(tissue_data['tomtom_stats'].get('e_value', 1))
                else:
                    significance = 0
                
                tissue_motifs.append((jaspar_id, significance))
        
        # Sort by significance and select top motifs
        tissue_motifs.sort(key=lambda x: x[1], reverse=True)
        selected_motifs = [x[0] for x in tissue_motifs[:max_motifs_per_tissue]]
        
        if not selected_motifs:
            print(f"No motifs found for tissue {target_tissue_id}")
            return
        
        # Get tissue name
        tissue_name = self.tissue_full_name_map.get(target_tissue_id, f"Tissue_{target_tissue_id}")
        
        print(f"\n[Top hits from {tissue_name}]")
        print(f"Selected motifs: {selected_motifs}")
        
        # First plot PWM sequence logos for selected motifs
        print("-- Motif PWMs --")
        for jaspar_id in selected_motifs:
            motif_data = self.motifs[jaspar_id]
            motif_name = motif_data.get('jaspar_motif_name', jaspar_id)
            print(f"{motif_name}")
            
            if 'jaspar_pwm' in motif_data:
                jaspar_pwm = motif_data['jaspar_pwm']
                
                # Plot JASPAR PWM
                fig_pwm = self.plot_pwm(jaspar_pwm, 
                                       figsize=(0.3 * jaspar_pwm.shape[0], 1.2), 
                                       y_min=0., y_max=2., plot_y_ticks=False,
                                       title=f"{motif_name}")
                
                # Save PWM plot
                pwm_save_path = os.path.join(self.output_dir, f"{save_prefix}_{tissue_name}_{jaspar_id}_pwm.{image_format}")
                plt.savefig(pwm_save_path, dpi=300, bbox_inches='tight', transparent=True)
                plt.show()
        
        # Then plot saliency distributions
        self._plot_motif_saliency_comparison(selected_motifs, tissue_name, save_prefix, 
                                           n_cols, col_width, y_min_fixed, y_max_fixed, image_format)
    
    def _plot_motif_saliency_comparison(self, selected_motifs, tissue_name, save_prefix, 
                                      n_cols, col_width, y_min_fixed, y_max_fixed, image_format='png'):
        """Plot saliency comparison for selected motifs across all tissues."""
        
        print("-- Motif Score Distributions --")
        
        n_motifs = len(selected_motifs)
        n_cols = min(n_cols, n_motifs)
        n_rows = (n_motifs + n_cols - 1) // n_cols
        
        for row_ix in range(n_rows):
            # Create figure for this row
            fig, axes = plt.subplots(1, n_cols, figsize=(col_width * n_cols, 4))
            if n_cols == 1:
                axes = [axes]
            
            col_start = row_ix * n_cols
            
            for motif_idx in range(col_start, min(col_start + n_cols, n_motifs)):
                col_i = motif_idx % n_cols
                ax = axes[col_i]
                
                jaspar_id = selected_motifs[motif_idx]
                motif_data = self.motifs[jaspar_id]
                motif_name = motif_data.get('jaspar_motif_name', jaspar_id)
                
                print(f"Motif = '{motif_name}'")
                
                # Prepare data for plotting across ALL tissues
                self._plot_single_motif_across_tissues(ax, jaspar_id, motif_data, motif_name, 
                                                     y_min_fixed, y_max_fixed, col_i, n_cols)
            
            # Hide empty subplots
            for empty_idx in range(min(col_start + n_cols, n_motifs), col_start + n_cols):
                if empty_idx - col_start < len(axes):
                    axes[empty_idx - col_start].set_visible(False)
            
            plt.tight_layout()
            
            # Save figure for this row
            save_path = os.path.join(self.output_dir, f"{save_prefix}_{tissue_name}_row_{row_ix}_scores.{image_format}")
            plt.savefig(save_path, dpi=600, bbox_inches='tight', transparent=True)
            print(f"Saved {tissue_name} row {row_ix} to {save_path}")
            
            plt.show()
    
    def _plot_single_motif_across_tissues(self, ax, jaspar_id, motif_data, motif_name, 
                                        y_min_fixed, y_max_fixed, col_i, n_cols):
        """Plot a single motif's saliency across all tissues."""
        
        # Prepare data for plotting across ALL tissues
        tissue_ids = []
        saliency_data = []
        tissue_names = []
        
        # Get all available tissues for this motif
        available_tissues = sorted(motif_data['tissues'].keys())
        print(f" - Available tissues: {available_tissues}")
        
        for tissue_id in available_tissues:
            tissue_data = motif_data['tissues'][tissue_id]
            # Prefer to recompute from grads_dir if provided
            scores = None
            if self.grads_dir:
                scores = self._compute_saliency_for_motif_tissue(jaspar_id, tissue_id)
            if scores is None or len(scores) == 0:
                # Fallback to precomputed scores in integrated H5
                scores = tissue_data.get('saliency_scores', np.array([]))
            if scores is None or len(scores) == 0:
                continue
            tissue_ids.append(tissue_id)
            saliency_data.append(scores)
            
            # Use short tissue names from class mapping
            tissue_names.append(self.tissue_name_map.get(tissue_id, f"T{tissue_id}"))
            
            # Debug: Print data info
            try:
                print(f" - Tissue {tissue_id}: {len(scores)} scores, range [{np.min(scores):.3f}, {np.max(scores):.3f}]")
            except Exception:
                print(f" - Tissue {tissue_id}: {len(scores)} scores")
        
        if not saliency_data:
            ax.text(0.5, 0.5, 'No data', ha='center', va='center', transform=ax.transAxes)
            ax.set_title(f"{motif_name}")
            return
        
        # Convert to numpy array for easier manipulation
        max_len = max(len(scores) for scores in saliency_data)
        saliency_matrix = np.full((max_len, len(tissue_ids)), np.nan)
        
        for i, scores in enumerate(saliency_data):
            saliency_matrix[:len(scores), i] = scores
        
        n_seqlets = len([x for x in saliency_matrix[:, 0] if not np.isnan(x)])
        print(f" - n = {n_seqlets}")
        
        # Calculate Wilcoxon p-values between tissues
        if n_seqlets > 10:
            for score_ix in range(len(tissue_ids)):
                for other_ix in range(len(tissue_ids)):
                    if score_ix != other_ix:
                        scores_1 = saliency_data[score_ix]
                        scores_2 = saliency_data[other_ix]
                        if len(scores_1) > 0 and len(scores_2) > 0:
                            s_val, p_val = ranksums(scores_1, scores_2, alternative='two-sided')
                            print(f" - Wilcoxon p ('{tissue_names[score_ix]}' vs '{tissue_names[other_ix]}') = {p_val:.2e} (s = {s_val:.2f})")
        
        # Plot strip plot using seaborn stripplot (like in reference)
        try:
            # Convert to format expected by seaborn: list of lists
            plot_data_transposed = [list(scores) for scores in saliency_data]
            sns.stripplot(data=plot_data_transposed, palette='dark:black', s=2, alpha=0.1, jitter=0.2, ax=ax)
        except Exception as e:
            # Fallback to manual implementation
            print(f"Seaborn stripplot failed: {e}, using manual implementation")
            for i, scores in enumerate(saliency_data):
                if len(scores) > 0:
                    # Add jitter to x positions
                    x_jitter = np.random.normal(i, 0.2, len(scores))
                    ax.scatter(x_jitter, scores, alpha=0.1, s=2, color='black')
        
        # Plot quantiles and markers following the reference style
        qtls = [0.05, 0.50, 0.95]
        shades = [1.0, 0.8, 0.6]  # Different shades as in reference
        markers = ['D', 'o', 'D']
        fill_between = True
        
        # Define tissue colors matching the reference
        tissue_color_map = ['red', 'darkblue', 'darkorange', 'brown', 'darkgreen']
        
        for i, (tissue_id, scores) in enumerate(zip(tissue_ids, saliency_data)):
            if i < len(tissue_color_map):
                color = tissue_color_map[i]
            else:
                color = self.tissue_colors.get(tissue_id, 'gray')
            
            if len(scores) > 0:
                min_qtl_val = y_max_fixed
                
                for qtl_ix, qtl in enumerate(qtls):
                    qtl_val = np.quantile(scores, q=qtl)
                    
                    # Draw quantile lines
                    ax.plot([i - 0.5, i + 0.5], [qtl_val, qtl_val], 
                           color=lighten_color(color, shades[qtl_ix]), 
                           linewidth=1, linestyle='-', zorder=-1000)
                    
                    # Draw markers at tissue center
                    if col_i < n_cols - 1 or i > 0:
                        ax.scatter([i], [qtl_val], 
                                 color=lighten_color(color, shades[qtl_ix]), s=30, 
                                 edgecolor='black', linewidth=0.75, marker=markers[qtl_ix])
                    else:
                        ax.scatter([i], [qtl_val], 
                                 color=lighten_color(color, shades[qtl_ix]), s=30, 
                                 edgecolor='black', linewidth=0.75, marker=markers[qtl_ix],
                                 label=f'{int(100 * qtl)}th p.')
                    
                    # Fill between quantiles for shading effect
                    if fill_between and qtl_ix > 0:
                        ax.fill_between(
                            [i - 0.5, i + 0.5],
                            [prev_qtl_val, prev_qtl_val],
                            [qtl_val, qtl_val],
                            color=lighten_color(color, shades[qtl_ix]),
                            alpha=0.25
                        )
                    
                    # Cache previous qtl value
                    prev_qtl_val = qtl_val
                    min_qtl_val = min(min_qtl_val, qtl_val)
                
                # Truncate at 0 and fill bottom area
                min_qtl_val = max(0., min_qtl_val)
                if fill_between and min_qtl_val > 0:
                    ax.fill_between(
                        [i - 0.5, i + 0.5],
                        [0, 0],
                        [min_qtl_val, min_qtl_val],
                        color=lighten_color(color, max(shades[0] - 0.2, 0.2)),
                        alpha=0.25
                    )
        
        # Styling
        ax.axhline(y=0., linewidth=1, linestyle='--', color='black', zorder=-1000)
        
        # Calculate dynamic Y-axis limits if data is outside fixed range
        if saliency_data:
            all_scores = np.concatenate(saliency_data)
            data_min = np.min(all_scores)
            data_max = np.max(all_scores)
            
            # Use dynamic range if data is outside fixed range
            if data_min < y_min_fixed or data_max > y_max_fixed:
                y_margin = (data_max - data_min) * 0.1
                ax.set_ylim(data_min - y_margin, data_max + y_margin)
                print(f" - Using dynamic Y-axis: [{data_min - y_margin:.3f}, {data_max + y_margin:.3f}]")
            else:
                ax.set_ylim(y_min_fixed, y_max_fixed)
                print(f" - Using fixed Y-axis: [{y_min_fixed}, {y_max_fixed}]")
        else:
            ax.set_ylim(y_min_fixed, y_max_fixed)
        
        # Set axis labels
        if col_i > 0:
            ax.set_yticklabels([])
        else:
            ax.tick_params(axis='y', labelsize=8)
            ax.yaxis.set_major_formatter(FormatStrFormatter('%.3f'))
            ax.set_ylabel('Gradient Saliency', fontsize=8)
        
        positions = range(len(tissue_ids))
        ax.set_xticks(positions)
        ax.set_xticklabels(tissue_names, fontsize=8, rotation=60)
        ax.set_xlim(-0.5, len(tissue_ids) - 0.5)
        
        # Set legend
        if col_i == n_cols - 1:
            ax.legend(fontsize=8, loc='upper right')
        
        # Title with motif name and sample size
        ax.set_title(f"{motif_name}\n(n = {n_seqlets})", fontsize=8)

    def create_motif_plots(self, target_tissue_id=19, max_motifs=3, image_format='png', 
                          y_min_fixed=-0.01, y_max_fixed=0.05):
        """Create tissue-specific motif plots."""
        print("Creating tissue-specific motif plots...")
        
        # Create the tissue-specific motif interpretation plot
        self.plot_tissue_specific_motifs(target_tissue_id=target_tissue_id, 
                                        max_motifs_per_tissue=max_motifs, 
                                        save_prefix="tissue_specific_motifs",
                                        y_min_fixed=y_min_fixed, y_max_fixed=y_max_fixed,
                                        image_format=image_format)
        
        print("Tissue-specific motif plots created successfully!")


def main():
    """Main function to run the plotting script."""
    parser = argparse.ArgumentParser(description='Create tissue-specific motif plots with PWM logos and saliency distributions')
    
    parser.add_argument('-i', '--input', required=True,
                       help='Input H5 file from motif_metadata_summary.py')
    parser.add_argument('-o', '--output_dir', default='plots',
                       help='Output directory for plots')
    parser.add_argument('-t', '--tissue_id', type=int, default=None,
                       help='Target tissue ID (if None, plot all tissues)')
    parser.add_argument('-m', '--max_motifs', type=int, default=10,
                       help='Maximum number of motifs per tissue')
    parser.add_argument('-f', '--format', choices=['png', 'jpg', 'jpeg', 'pdf', 'svg'], default='png',
                       help='Output image format (default: png)')
    parser.add_argument('-g', '--grads_dir', default=None,
                       help='Directory containing grads H5 files (e.g., 5tissues_grads/) to recompute saliency')
    parser.add_argument('--y-min', type=float, default=-0.001,
                       help='Minimum Y-axis value for saliency plots (default: -0.001)')
    parser.add_argument('--y-max', type=float, default=0.0001,
                       help='Maximum Y-axis value for saliency plots (default: 0.0001)')
    
    args = parser.parse_args()
    
    # Validate input file
    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' not found")
        sys.exit(1)
    
    # Create plotter and generate plots
    plotter = MotifPlotter(args.input, args.output_dir, grads_dir=args.grads_dir)
    plotter.create_motif_plots(target_tissue_id=args.tissue_id, max_motifs=args.max_motifs, 
                              image_format=args.format, y_min_fixed=args.y_min, y_max_fixed=args.y_max)


if __name__ == '__main__':
    main()
